### ISSUE TITLE
Other Language Support

### ISSUE THREAD

**Issue by B0rbor4d** [mrthinger/wow-voiceover#86]
I really love what you did here <3

as I'm a native German speaker I wonder if you've ever planed to support other languages then English or maybe would accept help for such??

Keep the work
/cheers B!!

**Comment by jbusodev** [comment]
**TL:;DR: ** The author does not plan to implement other languages, but he is open to people taking it upon themselves to implement them, given the additional storage space that it is going to involve (for all texts and sound files in every single language)

Hey, since a lot of people are wondering this, and the author does not respond to all questions about that subject, I just thought I would share the answer I found. For more up-to-date information on that, feel free to join the discord where you'll find other developers and people who have the same intention to work towards implementing other languages.

**Comment by mrthinger** [comment]
This is being coordinated in the multilang channel of our discord: https://discord.gg/yretmJRFm4
